name: Main

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x

    - uses: actions/checkout@v2

    - name: Build & Test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      run: |
        dotnet build
        dotnet run --project ./tests/FSharp.Core.Extensions.Tests
